// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    GetHealth429Response,
    GetHealth429ResponseFromJSON,
    GetHealth429ResponseToJSON,
    GetV1RunnerModels200Response,
    GetV1RunnerModels200ResponseFromJSON,
    GetV1RunnerModels200ResponseToJSON,
    PostV1RunnerChat200Response,
    PostV1RunnerChat200ResponseFromJSON,
    PostV1RunnerChat200ResponseToJSON,
    PostV1RunnerChatRequest,
    PostV1RunnerChatRequestFromJSON,
    PostV1RunnerChatRequestToJSON,
    PostV1RunnerGenerateRequest,
    PostV1RunnerGenerateRequestFromJSON,
    PostV1RunnerGenerateRequestToJSON,
} from '../models';

export interface PostV1RunnerChatRequest {
    postV1RunnerChatRequest: PostV1RunnerChatRequest;
}

export interface PostV1RunnerGenerateRequest {
    postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest;
}


/**
 * 
 * List configured runner model routes
 */
function getV1RunnerModelsRaw<T>( requestConfig: runtime.TypedQueryConfig<T, GetV1RunnerModels200Response> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/runner/models`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(GetV1RunnerModels200ResponseFromJSON(body), text);
    }

    return config;
}

/**
* 
* List configured runner model routes
*/
export function getV1RunnerModels<T>( requestConfig?: runtime.TypedQueryConfig<T, GetV1RunnerModels200Response>): QueryConfig<T> {
    return getV1RunnerModelsRaw( requestConfig);
}

/**
 * 
 * Multi-turn chat completion
 */
function postV1RunnerChatRaw<T>(requestParameters: PostV1RunnerChatRequest, requestConfig: runtime.TypedQueryConfig<T, PostV1RunnerChat200Response> = {}): QueryConfig<T> {
    if (requestParameters.postV1RunnerChatRequest === null || requestParameters.postV1RunnerChatRequest === undefined) {
        throw new runtime.RequiredError('postV1RunnerChatRequest','Required parameter requestParameters.postV1RunnerChatRequest was null or undefined when calling postV1RunnerChat.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/runner/chat`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || PostV1RunnerChatRequestToJSON(requestParameters.postV1RunnerChatRequest),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(PostV1RunnerChat200ResponseFromJSON(body), text);
    }

    return config;
}

/**
* 
* Multi-turn chat completion
*/
export function postV1RunnerChat<T>(requestParameters: PostV1RunnerChatRequest, requestConfig?: runtime.TypedQueryConfig<T, PostV1RunnerChat200Response>): QueryConfig<T> {
    return postV1RunnerChatRaw(requestParameters, requestConfig);
}

/**
 * 
 * Single-prompt generation
 */
function postV1RunnerGenerateRaw<T>(requestParameters: PostV1RunnerGenerateRequest, requestConfig: runtime.TypedQueryConfig<T, PostV1RunnerChat200Response> = {}): QueryConfig<T> {
    if (requestParameters.postV1RunnerGenerateRequest === null || requestParameters.postV1RunnerGenerateRequest === undefined) {
        throw new runtime.RequiredError('postV1RunnerGenerateRequest','Required parameter requestParameters.postV1RunnerGenerateRequest was null or undefined when calling postV1RunnerGenerate.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/runner/generate`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || PostV1RunnerGenerateRequestToJSON(requestParameters.postV1RunnerGenerateRequest),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(PostV1RunnerChat200ResponseFromJSON(body), text);
    }

    return config;
}

/**
* 
* Single-prompt generation
*/
export function postV1RunnerGenerate<T>(requestParameters: PostV1RunnerGenerateRequest, requestConfig?: runtime.TypedQueryConfig<T, PostV1RunnerChat200Response>): QueryConfig<T> {
    return postV1RunnerGenerateRaw(requestParameters, requestConfig);
}

