// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    GetHealth200Response,
    GetHealth200ResponseFromJSON,
    GetHealth200ResponseToJSON,
    GetHealth429Response,
    GetHealth429ResponseFromJSON,
    GetHealth429ResponseToJSON,
} from '../models';


/**
 * Returns server health status
 * Health check
 */
function getHealthRaw<T>( requestConfig: runtime.TypedQueryConfig<T, GetHealth200Response> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/health`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(GetHealth200ResponseFromJSON(body), text);
    }

    return config;
}

/**
* Returns server health status
* Health check
*/
export function getHealth<T>( requestConfig?: runtime.TypedQueryConfig<T, GetHealth200Response>): QueryConfig<T> {
    return getHealthRaw( requestConfig);
}

