// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response  {
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    data?: string;
    /**
     * 
     * @type {Error}
     * @memberof GetHealth200Response
     */
    error?: Error;
    /**
     * 
     * @type {Meta}
     * @memberof GetHealth200Response
     */
    meta?: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof GetHealth200Response
     */
    success: boolean;
}

export function GetHealth200ResponseFromJSON(json: any): GetHealth200Response {
    return {
        'data': !exists(json, 'data') ? undefined : json['data'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'success': json['success'],
    };
}

export function GetHealth200ResponseToJSON(value?: GetHealth200Response): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': value.data,
        'error': value.error,
        'meta': MetaToJSON(value.meta),
        'success': value.success,
    };
}


