// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetV1RunnerModels200ResponseData,
    GetV1RunnerModels200ResponseDataFromJSON,
    GetV1RunnerModels200ResponseDataToJSON,
    Meta,
    MetaFromJSON,
    MetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetV1RunnerModels200Response
 */
export interface GetV1RunnerModels200Response  {
    /**
     * 
     * @type {GetV1RunnerModels200ResponseData}
     * @memberof GetV1RunnerModels200Response
     */
    data?: GetV1RunnerModels200ResponseData;
    /**
     * 
     * @type {Error}
     * @memberof GetV1RunnerModels200Response
     */
    error?: Error;
    /**
     * 
     * @type {Meta}
     * @memberof GetV1RunnerModels200Response
     */
    meta?: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof GetV1RunnerModels200Response
     */
    success: boolean;
}

export function GetV1RunnerModels200ResponseFromJSON(json: any): GetV1RunnerModels200Response {
    return {
        'data': !exists(json, 'data') ? undefined : GetV1RunnerModels200ResponseDataFromJSON(json['data']),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'success': json['success'],
    };
}

export function GetV1RunnerModels200ResponseToJSON(value?: GetV1RunnerModels200Response): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': GetV1RunnerModels200ResponseDataToJSON(value.data),
        'error': value.error,
        'meta': MetaToJSON(value.meta),
        'success': value.success,
    };
}


