// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meta
 */
export interface Meta  {
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    duration?: string;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    perPage?: number;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    requestId?: string;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    total?: number;
}

export function MetaFromJSON(json: any): Meta {
    return {
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'perPage': !exists(json, 'per_page') ? undefined : json['per_page'],
        'requestId': !exists(json, 'request_id') ? undefined : json['request_id'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function MetaToJSON(value?: Meta): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'duration': value.duration,
        'page': value.page,
        'per_page': value.perPage,
        'request_id': value.requestId,
        'total': value.total,
    };
}


