// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError  {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    details?: any;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    message: string;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return {
        'code': json['code'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'message': json['message'],
    };
}

export function ModelErrorToJSON(value?: ModelError): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'code': value.code,
        'details': value.details,
        'message': value.message,
    };
}


