// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostV1RunnerGenerateRequest
 */
export interface PostV1RunnerGenerateRequest  {
    /**
     * 
     * @type {string}
     * @memberof PostV1RunnerGenerateRequest
     */
    prompt: string;
}

export function PostV1RunnerGenerateRequestFromJSON(json: any): PostV1RunnerGenerateRequest {
    return {
        'prompt': json['prompt'],
    };
}

export function PostV1RunnerGenerateRequestToJSON(value?: PostV1RunnerGenerateRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'prompt': value.prompt,
    };
}


