// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostV1RunnerChatRequestMessagesInner,
    PostV1RunnerChatRequestMessagesInnerFromJSON,
    PostV1RunnerChatRequestMessagesInnerToJSON,
} from './';

/**
 * 
 * @export
 * @interface PostV1RunnerChatRequest
 */
export interface PostV1RunnerChatRequest  {
    /**
     * 
     * @type {Array<PostV1RunnerChatRequestMessagesInner>}
     * @memberof PostV1RunnerChatRequest
     */
    messages: Array<PostV1RunnerChatRequestMessagesInner>;
}

export function PostV1RunnerChatRequestFromJSON(json: any): PostV1RunnerChatRequest {
    return {
        'messages': (json['messages'] as Array<any>).map(PostV1RunnerChatRequestMessagesInnerFromJSON),
    };
}

export function PostV1RunnerChatRequestToJSON(value?: PostV1RunnerChatRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'messages': (value.messages as Array<any>).map(PostV1RunnerChatRequestMessagesInnerToJSON),
    };
}


