// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostV1RunnerChat200ResponseData
 */
export interface PostV1RunnerChat200ResponseData  {
    /**
     * 
     * @type {string}
     * @memberof PostV1RunnerChat200ResponseData
     */
    reply?: string;
}

export function PostV1RunnerChat200ResponseDataFromJSON(json: any): PostV1RunnerChat200ResponseData {
    return {
        'reply': !exists(json, 'reply') ? undefined : json['reply'],
    };
}

export function PostV1RunnerChat200ResponseDataToJSON(value?: PostV1RunnerChat200ResponseData): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'reply': value.reply,
    };
}


