// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaToJSON,
    PostV1RunnerChat200ResponseData,
    PostV1RunnerChat200ResponseDataFromJSON,
    PostV1RunnerChat200ResponseDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface PostV1RunnerChat200Response
 */
export interface PostV1RunnerChat200Response  {
    /**
     * 
     * @type {PostV1RunnerChat200ResponseData}
     * @memberof PostV1RunnerChat200Response
     */
    data?: PostV1RunnerChat200ResponseData;
    /**
     * 
     * @type {Error}
     * @memberof PostV1RunnerChat200Response
     */
    error?: Error;
    /**
     * 
     * @type {Meta}
     * @memberof PostV1RunnerChat200Response
     */
    meta?: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof PostV1RunnerChat200Response
     */
    success: boolean;
}

export function PostV1RunnerChat200ResponseFromJSON(json: any): PostV1RunnerChat200Response {
    return {
        'data': !exists(json, 'data') ? undefined : PostV1RunnerChat200ResponseDataFromJSON(json['data']),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'success': json['success'],
    };
}

export function PostV1RunnerChat200ResponseToJSON(value?: PostV1RunnerChat200Response): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': PostV1RunnerChat200ResponseDataToJSON(value.data),
        'error': value.error,
        'meta': MetaToJSON(value.meta),
        'success': value.success,
    };
}


